build:
  stage: build
  image: ubuntu:20.10
  script:
    - apt update
    - apt install -y buildah
    - export BUILDAH_FORMAT=docker IMAGE_NAME="$CI_REGISTRY_IMAGE:latest"
    - echo $CI_REGISTRY_PASSWORD | buildah login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - buildah bud -t $IMAGE_NAME .
    - buildah push $IMAGE_NAME
