build:
  stage: build
  image: ubuntu:20.10
  script:
    - apt update
    - apt install -y buildah runc ca-certificates

    - export BUILDAH_FORMAT=docker
    - echo $CI_REGISTRY_PASSWORD | buildah login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

    - buildah bud -t $CI_REGISTRY_IMAGE:latest .
    - buildah push $CI_REGISTRY_IMAGE:latest
